=== designfusionjb/DirSyncro/DirSyncro/Configuration/DirSyncro.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (x64) (http://www.altova.com) by Mattias Jonsson (Private User) -->
<xs:schema xmlns="DirSyncroConfiguration" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="DirSyncroConfiguration" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DirSyncro">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Watcher" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="SourceDirectory" type="xs:string"/>
							<xs:element name="TargetDirectory" type="xs:string" maxOccurs="unbounded"/>
							<xs:element name="Recursive" type="xs:boolean"/>
							<xs:element name="Versions" type="xs:int"/>
							<xs:element name="Settling" type="xs:long"/>
							<xs:element name="Retention" type="xs:long"/>
							<xs:element name="Include" type="xs:string"/>
							<xs:element name="Exclude" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="Name" type="xs:string" use="required"/>
						<xs:attribute name="Enabled" type="xs:boolean" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== designfusionjb/DirSyncro/DirSyncro/DirSyncro.xml
<?xml version="1.0" encoding="UTF-8"?>
<DirSyncro xsi:schemaLocation="DirSyncroConfiguration DirSyncro.xsd" xmlns="DirSyncroConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Watcher Name="Watcher 1" Enabled="true">
    <SourceDirectory>C:\Temp</SourceDirectory>
    <TargetDirectory>C:\Target1</TargetDirectory>
    <Recursive>true</Recursive>
    <Versions>3</Versions>
    <Settling>10000</Settling>
    <Retention>100</Retention>
    <Include></Include>
    <Exclude>*.tmp; ~*.docx</Exclude>
  </Watcher>
</DirSyncro>
